context:
  version: "0.17.0"

package:
  name: ndonnx
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/n/ndonnx/ndonnx-${{ version }}.tar.gz
    sha256: 9613aafa7bb3c5c760882e4d2709ce2c1e22366d97b576b213de1ca134cbeaaa

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - onnx
    - spox >=0.10
    - typing-extensions

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - ndonnx
      pip_check: true

about:
  homepage: https://github.com/quantco/ndonnx
  summary: ONNX backed array library compliant with Array API standard.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adityagoel4512
    - cbourjau
