context:
  version: "0.23.0"

package:
  name: ndonnx
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/n/ndonnx/ndonnx-${{ version }}.tar.gz
    sha256: 3e7e2e0001f2a9c2a77e6ae191513d00bbc388dcca2ff13b8ed4a5cde5c302d1

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - onnx
    - spox >=0.10
    - typing-extensions

tests:
  - python:
      imports:
        - ndonnx
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  homepage: https://github.com/quantco/ndonnx
  summary: ONNX backed array library compliant with Array API standard.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbourjau
    - sgilm
